# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: organization-service
plugins:
  - serverless-offline
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'local'}
  profile: rest-app
  region: us-west-2
  versionFunctions: false

custom: ${file(./environment.json)}

functions:
  createOrganization:
    handler: organization.create
    events:
      - httpApi:
          path: /organization
          method: POST
          cors: true
  getOrganization:
    handler: organization.get
    events:
      - httpApi:
          path: /organization
          method: GET
          cors: true
      - kafka:
          accessConfigurations:
            saslScram512Auth: ${self:custom.SASL_SCRAM_512_AUTH}
          topic: organization-get-${opt:stage, 'local'}
          bootstrapServers:
            - ${self:custom.KAFKA_SERVER}
          enabled: true
  updateOrganization:
    handler: organization.update
    events:
      - httpApi:
          path: /organization
          method: PUT
          cors: true
  deleteOrganization:
    handler: organization.del
    events:
      - httpApi:
          path: /organization
          method: DELETE
          cors: true

# you can add CloudFormation resource templates here
resources:
  serverless-offline:
    httpPort: 4100
    useChildProcesses: true
